/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.jupiter.api.Test;

import java.awt.*;
import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    App classUnderTest = new App();

    Bitmap sample=new Bitmap("build/resources/main/inputFile.bmp","build/resources/main/outputFile.bmp");

    AppTest() throws IOException {
    }


    @Test void black_white() throws IOException {
        assertEquals("no problem", sample.black_And_white_status, "Ensure black_white function have no error");
         sample.black_white(Color.BLACK);
         sample.black_white(null);
    }
    @Test void Flip() throws IOException {
        assertEquals("no problem", sample.flip_status, "Ensure flip function have no error");
        sample.flip(90.0);
        sample.flip(-180.0);
    }
    @Test void Darken() throws IOException {
        assertEquals("no problem", sample.darken_status, "Ensure darken function have no error");
        sample.Darken(50.0);
        sample.Darken(0.0);


    }
}
